project:
  type: website

  # only these two qmds get rendered
  files:
    - course_guide.qmd
    - code_annex.qmd

website:
  title: "MA206X"
  navbar:
    left:
      - href: course_guide.qmd
        text: Home
      - href: code_annex.qmd
        text: Code Annex

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: false
    page-layout: full
    fig-align: center
    css: styles.css

editor: visual