name: Publish Quarto Website

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # ✅ Install R
      - uses: r-lib/actions/setup-r@v2

      # ✅ Install Quarto
      - uses: quarto-dev/quarto-actions/setup@v2

      # ✅ Install R packages you need (like tidyverse, etc.)
      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('tidyverse', 'titanic', 'knitr'), repos='https://cloud.r-project.org')"

      # ✅ Render the site
      - name: Render website
        run: quarto render

      # ✅ Deploy to GitHub Pages
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
